### ISSUE TITLE
I don't think this is working any more

### ISSUE THREAD

**Issue by leonsparrowJM** [jhutchings1/conda-dependency-submission-action#24]
The manifests payload is empty when it should have some dependencies listed.

**Comment by leonsparrowJM** [comment]
I get this error:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ too

**Comment by jhutchings1** [comment]
I updated the environment and dependencies. It should be working again. Enjoy!
